name: docker
version: 1.0
rundeckPluginVersion: 1.1
author: Adam Avilla
date: 03/02/16
providers:
  - name: docker
    service: WorkflowNodeStep
    title: 'docker'
    description: Execute a docker container on a node with dockerPluginType defined.
    plugin-type: script
    script-file: rundeck-docker-plugin
    config:
      - type: String
        name: docker_image
        title: Image
        description: 'The docker image to run.'
        required: true
      - type: String
        name: docker_command
        title: Command
        description: 'What command should the container run.'
      - type: String
        name: docker_cpus
        title: CPUs
        description: 'How many cpus your container needs.'
        required: true
        default: 1
      - type: String
        name: docker_memory
        title: Memory
        description: 'How much memory your container needs.'
        required: true
        default: 10
      - type: String
        name: docker_env_vars
        title: Environment Vars
        description: 'String of newline separated bash env variables. E.g. FOO=bar\nBANG=bazz'
        renderingOptions:
          displayType: MULTI_LINE
      - type: Boolean
        name: docker_pull_image
        title: Pull image?
        description: 'Check if you would like to pull the image before running it.'
      - type: String
        name: docker_mesos_principal
        title: Principal
        description: 'Principal for authentication to mesos.'
        scope: Project
      - type: String
        name: docker_mesos_secret
        title: Secret
        description: 'Secret for authentication to mesos.'
        scope: Project
      - type: String
        name: docker_mesos_user
        title: User
        description: 'User to run tasks on mesos as.'
        default: root
        scope: Project
      - type: String
        name: docker_registry_username
        title: Username
        description: 'Username for authentication to docker registry.'
        scope: Project
      - type: String
        name: docker_registry_password
        title: Password
        description: 'Password for authentication to docker registry.'
        scope: Project
